### ISSUE TITLE
How to read the plot

### ISSUE THREAD

**Issue by bob100077** [isabelschober/proteinortho_curves#1]
Hi,
Could you describe the plot produced by this code?
For example, what do the dots and the bot plot bars represent? Are they error bars and outliers? How are these produced?
Is there a way to calculate Heap's law for open/closed pan-genomes using this script?

Thanks!

**Comment by isabelschober** [comment]
Hi,

the boxplots are drawn with ggplot2's geom_boxplot function. You can find an explanation of what is presented how here: https://ggplot2.tidyverse.org/reference/geom_boxplot.html#summary-statistics

This script doesn't calculate a regression and doesn't fit any curves using Heap's law, sorry.
