### ISSUE TITLE
The format of Input Data

### ISSUE THREAD

**Issue by zhangqing970** [isabelschober/proteinortho_curves#2]
Hi, can you upload the example input data? Thanks for your help!

**Comment by isabelschober** [comment]
Hi,

the input data should be the tab-separated output from a Proteinortho run.

You can find information about it here: http://legacy.bioinf.uni-leipzig.de/Software/proteinortho/manual.html

In short, it should look like this:
```
# Species	Genes	Alg.-Conn.	M.faa	L.faa	C.faa		E.faa
4		4	1		M_10	L_10	C_10		E_10
4		4	1		M_11	L_11	C_11		E_11
4		4	1		M_14	L_14	C_14		E_14
...
4		5	0.2		M_19	L_19	C_22,C_63	E_19
...
```

**Comment by zhangqing970** [comment]
Got it , thanks for your help!
